export const courseModules = [
  {
    id: "python-basics",
    title: "Python Basics",
    type: "basic" as const,
    description: "Learn Python syntax, data types, and basic programming concepts",
    sessions: 5,
    price: 99,
    topics: [
      "Python installation and setup",
      "Variables and data types",
      "Control flow (if/else, loops)",
      "Functions and modules",
      "Basic error handling",
    ],
    practices: ["Create a simple calculator", "Build a temperature converter", "Implement a number guessing game"],
  },
  {
    id: "data-structures",
    title: "Data Structures",
    type: "basic" as const,
    description: "Master Python data structures like lists, dictionaries, and sets",
    sessions: 4,
    price: 79,
    topics: ["Lists and tuples", "Dictionaries and sets", "List comprehensions", "Working with collections module"],
    practices: ["Implement a contact book", "Create a word frequency counter", "Build a simple inventory system"],
  },
  {
    id: "oop-python",
    title: "Object-Oriented Programming",
    type: "basic" as const,
    description: "Learn OOP principles and how to implement them in Python",
    sessions: 5,
    price: 99,
    topics: [
      "Classes and objects",
      "Inheritance and polymorphism",
      "Encapsulation and abstraction",
      "Magic methods",
      "Property decorators",
    ],
    practices: [
      "Design a bank account system",
      "Create a simple game with classes",
      "Build a library management system",
    ],
  },
  {
    id: "data-analysis",
    title: "Data Analysis with Pandas",
    type: "advanced" as const,
    description: "Learn to analyze and manipulate data using Pandas",
    sessions: 6,
    price: 149,
    topics: [
      "Introduction to NumPy",
      "Pandas DataFrame basics",
      "Data cleaning and preprocessing",
      "Data visualization with Matplotlib",
      "Statistical analysis",
      "Working with time series data",
    ],
    practices: ["Analyze a real-world dataset", "Create insightful visualizations", "Build a data dashboard"],
  },
  {
    id: "web-development",
    title: "Web Development with Flask",
    type: "advanced" as const,
    description: "Build web applications using the Flask framework",
    sessions: 7,
    price: 179,
    topics: [
      "Flask basics",
      "Routing and views",
      "Templates with Jinja2",
      "Forms and validation",
      "Database integration with SQLAlchemy",
      "RESTful API development",
      "Deployment",
    ],
    practices: ["Create a personal blog", "Build a RESTful API", "Develop a full-stack web application"],
  },
  {
    id: "machine-learning",
    title: "Machine Learning Fundamentals",
    type: "advanced" as const,
    description: "Introduction to machine learning concepts and implementations",
    sessions: 8,
    price: 199,
    topics: [
      "Introduction to ML concepts",
      "Supervised learning",
      "Unsupervised learning",
      "Model evaluation",
      "Scikit-learn library",
      "Linear regression",
      "Classification algorithms",
      "Model deployment",
    ],
    practices: ["Predict house prices with regression", "Build a spam classifier", "Create a recommendation system"],
  },
  {
    id: "automation",
    title: "Python Automation",
    type: "advanced" as const,
    description: "Learn to automate tasks with Python",
    sessions: 5,
    price: 129,
    topics: [
      "Working with files and directories",
      "Web scraping with BeautifulSoup",
      "Browser automation with Selenium",
      "Task scheduling",
      "Creating desktop applications with Tkinter",
    ],
    practices: ["Build a web scraper", "Create an automated file organizer", "Develop a GUI application"],
  },
]
